unbind C-b
set-option -g prefix `
bind ` send-prefix

# https://github.com/tmux-plugins/tpm/blob/master/docs/tpm_not_working.md#:~:text=installed%20using%20brew)-,Related%3A%20issue%20%2367,-This%20problem%20is
# '~/.tmux/plugins/tpm/tpm' returned 127 (on macOS, w/ tmux installed using brew)
# This problem is because tmux's run-shell command runs a shell which doesn't read from user configs, thus 
# tmux installed in a brew prefix (e.g. /usr/local/bin) will not be found.
set-environment -g PATH "/opt/homebrew/bin:/bin:/usr/bin"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'jimeh/tmux-themepack'
set -g @themepack 'powerline/default/cyan'

# - Vim key-bindings ----------

# Set vi mode for navigating terminal window with vim keys
setw -g mode-keys vi

# - windows -------------------
set -g renumber-windows on    # renumber windows when a window is closed

# - navigation ----------------

# split current window horizontally
bind - split-window -v -c "#{pane_current_path}"

# split current window veritcally
bind _ split-window -h -c "#{pane_current_path}"

# pane navigation
bind-key -r h select-pane -L  # move left
bind-key -r j select-pane -D  # move down
bind-key -r k select-pane -U  # move up
bind-key -r l select-pane -R  # move right

# Easy resizing of panes
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r H resize-pane -L 5
bind -r L resize-pane -R 5

# - mouse ----------------------

# Mouse support - set to on if you want to use the mouse
set -g mouse on

# Update this to your python's site-packages folder
if-shell -b '[ "$(uname -m)" = "x86_64" ]' {
  source "/usr/local/lib/python3.12/site-packages/powerline/bindings/tmux/powerline.conf"
}

if-shell -b '[ "$(uname -m)" = "arm64" ]' {
  source "/opt/homebrew/lib/python3.12/site-packages/powerline/bindings/tmux/powerline.conf"
}

# POPUP WINDOWS
# These two shortcuts provide popup windows in tmux. The lowercase version
# makes a popup that named uniquely to the working directory. This is great
# for making a popup window in a coding project.
#
# The uppercase version makes a "global" popup window. Great for persisting
# things globally for a long period of time.
bind g run-shell '\
    POPUP_NAME="popup-$(basename "#{pane_current_path}" | tr -cd "a-zA-Z0-9-")"; \
    if [ "#{session_name}" = "$POPUP_NAME" ]; then \
        tmux detach-client; \
    else \
        tmux display-popup -d "#{pane_current_path}" -xC -yC -w 80% -h 75% -E "tmux attach-session -t $POPUP_NAME || tmux new-session -s $POPUP_NAME"; \
    fi \
'

bind G run-shell '\
    POPUP_NAME="popup-global"; \
    if [ "#{session_name}" = "$POPUP_NAME" ]; then \
        tmux detach-client; \
    else \
        tmux display-popup -xC -yC -w 80% -h 75% -E "tmux attach-session -t $POPUP_NAME || tmux new-session -s $POPUP_NAME"; \
    fi \
'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
